// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

public final class FlatMessageBodyUnion {
  private FlatMessageBodyUnion() { }
  public static final byte NONE = 0;
  public static final byte FlatGameWorld = 1;

  private static final String[] names = { "NONE", "FlatGameWorld", };

  public static String name(int e) { return names[e]; }
};

