// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlatClientIDComponent extends Table {
  public static FlatClientIDComponent getRootAsFlatClientIDComponent(ByteBuffer _bb) { return getRootAsFlatClientIDComponent(_bb, new FlatClientIDComponent()); }
  public static FlatClientIDComponent getRootAsFlatClientIDComponent(ByteBuffer _bb, FlatClientIDComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FlatClientIDComponent __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int clientID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFlatClientIDComponent(FlatBufferBuilder builder,
      int clientID) {
    builder.startObject(1);
    FlatClientIDComponent.addClientID(builder, clientID);
    return FlatClientIDComponent.endFlatClientIDComponent(builder);
  }

  public static void startFlatClientIDComponent(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addClientID(FlatBufferBuilder builder, int clientID) { builder.addInt(0, clientID, 0); }
  public static int endFlatClientIDComponent(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

