#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/MultiScreenGameEngine.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/net.jar:$APPDIR/lib/FlatBuffers.jar:$APPDIR/lib/MSGEStd.jar:$APPDIR/lib/box2d_processing.jar:$APPDIR/lib/jbox2d-library-2.2.1-ds.jar" MultiScreenGameEngine "$@"
