// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlatSimpleSpriteRenderComponent extends Table {
  public static FlatSimpleSpriteRenderComponent getRootAsFlatSimpleSpriteRenderComponent(ByteBuffer _bb) { return getRootAsFlatSimpleSpriteRenderComponent(_bb, new FlatSimpleSpriteRenderComponent()); }
  public static FlatSimpleSpriteRenderComponent getRootAsFlatSimpleSpriteRenderComponent(ByteBuffer _bb, FlatSimpleSpriteRenderComponent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FlatSimpleSpriteRenderComponent __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String spriteName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer spriteNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createFlatSimpleSpriteRenderComponent(FlatBufferBuilder builder,
      int spriteNameOffset) {
    builder.startObject(1);
    FlatSimpleSpriteRenderComponent.addSpriteName(builder, spriteNameOffset);
    return FlatSimpleSpriteRenderComponent.endFlatSimpleSpriteRenderComponent(builder);
  }

  public static void startFlatSimpleSpriteRenderComponent(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSpriteName(FlatBufferBuilder builder, int spriteNameOffset) { builder.addOffset(0, spriteNameOffset, 0); }
  public static int endFlatSimpleSpriteRenderComponent(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

