// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

public final class FlatComponentUnion {
  private FlatComponentUnion() { }
  public static final byte NONE = 0;
  public static final byte FlatSimpleSpriteRenderComponent = 1;
  public static final byte FlatRotatedSpriteRenderComponent = 2;
  public static final byte FlatRenderComponent = 3;
  public static final byte FlatTranslateOverTimeComponent = 4;
  public static final byte FlatRotateOverTimeComponent = 5;
  public static final byte FlatScaleOverTimeComponent = 6;

  private static final String[] names = { "NONE", "FlatSimpleSpriteRenderComponent", "FlatRotatedSpriteRenderComponent", "FlatRenderComponent", "FlatTranslateOverTimeComponent", "FlatRotateOverTimeComponent", "FlatScaleOverTimeComponent", };

  public static String name(int e) { return names[e]; }
};

