// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlatInitializationMessage extends Table {
  public static FlatInitializationMessage getRootAsFlatInitializationMessage(ByteBuffer _bb) { return getRootAsFlatInitializationMessage(_bb, new FlatInitializationMessage()); }
  public static FlatInitializationMessage getRootAsFlatInitializationMessage(ByteBuffer _bb, FlatInitializationMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FlatInitializationMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int clientID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFlatInitializationMessage(FlatBufferBuilder builder,
      int clientID) {
    builder.startObject(1);
    FlatInitializationMessage.addClientID(builder, clientID);
    return FlatInitializationMessage.endFlatInitializationMessage(builder);
  }

  public static void startFlatInitializationMessage(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addClientID(FlatBufferBuilder builder, int clientID) { builder.addInt(0, clientID, 0); }
  public static int endFlatInitializationMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

