// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

public final class FlatComponentUnion {
  private FlatComponentUnion() { }
  public static final byte NONE = 0;
  public static final byte FlatRenderComponent = 1;
  public static final byte FlatPerspectiveCameraComponent = 2;
  public static final byte FlatTranslateOverTimeComponent = 3;
  public static final byte FlatRotateOverTimeComponent = 4;
  public static final byte FlatScaleOverTimeComponent = 5;

  private static final String[] names = { "NONE", "FlatRenderComponent", "FlatPerspectiveCameraComponent", "FlatTranslateOverTimeComponent", "FlatRotateOverTimeComponent", "FlatScaleOverTimeComponent", };

  public static String name(int e) { return names[e]; }
};

