// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlatMessageBodyTable extends Table {
  public static FlatMessageBodyTable getRootAsFlatMessageBodyTable(ByteBuffer _bb) { return getRootAsFlatMessageBodyTable(_bb, new FlatMessageBodyTable()); }
  public static FlatMessageBodyTable getRootAsFlatMessageBodyTable(ByteBuffer _bb, FlatMessageBodyTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FlatMessageBodyTable __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte bodyType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table body(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createFlatMessageBodyTable(FlatBufferBuilder builder,
      byte body_type,
      int bodyOffset) {
    builder.startObject(2);
    FlatMessageBodyTable.addBody(builder, bodyOffset);
    FlatMessageBodyTable.addBodyType(builder, body_type);
    return FlatMessageBodyTable.endFlatMessageBodyTable(builder);
  }

  public static void startFlatMessageBodyTable(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addBodyType(FlatBufferBuilder builder, byte bodyType) { builder.addByte(0, bodyType, 0); }
  public static void addBody(FlatBufferBuilder builder, int bodyOffset) { builder.addOffset(1, bodyOffset, 0); }
  public static int endFlatMessageBodyTable(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

