// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlatMessage extends Table {
  public static FlatMessage getRootAsFlatMessage(ByteBuffer _bb) { return getRootAsFlatMessage(_bb, new FlatMessage()); }
  public static FlatMessage getRootAsFlatMessage(ByteBuffer _bb, FlatMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FlatMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public FlatMessageHeader header() { return header(new FlatMessageHeader()); }
  public FlatMessageHeader header(FlatMessageHeader obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public FlatMessageBodyTable bodyTable() { return bodyTable(new FlatMessageBodyTable()); }
  public FlatMessageBodyTable bodyTable(FlatMessageBodyTable obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createFlatMessage(FlatBufferBuilder builder,
      int headerOffset,
      int bodyTableOffset) {
    builder.startObject(2);
    FlatMessage.addBodyTable(builder, bodyTableOffset);
    FlatMessage.addHeader(builder, headerOffset);
    return FlatMessage.endFlatMessage(builder);
  }

  public static void startFlatMessage(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addHeader(FlatBufferBuilder builder, int headerOffset) { builder.addOffset(0, headerOffset, 0); }
  public static void addBodyTable(FlatBufferBuilder builder, int bodyTableOffset) { builder.addOffset(1, bodyTableOffset, 0); }
  public static int endFlatMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFlatMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
};

