// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlatComponentTable extends Table {
  public static FlatComponentTable getRootAsFlatComponentTable(ByteBuffer _bb) { return getRootAsFlatComponentTable(_bb, new FlatComponentTable()); }
  public static FlatComponentTable getRootAsFlatComponentTable(ByteBuffer _bb, FlatComponentTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FlatComponentTable __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public byte componentType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table component(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o) : null; }

  public static int createFlatComponentTable(FlatBufferBuilder builder,
      byte component_type,
      int componentOffset) {
    builder.startObject(2);
    FlatComponentTable.addComponent(builder, componentOffset);
    FlatComponentTable.addComponentType(builder, component_type);
    return FlatComponentTable.endFlatComponentTable(builder);
  }

  public static void startFlatComponentTable(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addComponentType(FlatBufferBuilder builder, byte componentType) { builder.addByte(0, componentType, 0); }
  public static void addComponent(FlatBufferBuilder builder, int componentOffset) { builder.addOffset(1, componentOffset, 0); }
  public static int endFlatComponentTable(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

