// automatically generated by the FlatBuffers compiler, do not modify

package msge.std;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FlatModel extends Table {
  public static FlatModel getRootAsFlatModel(ByteBuffer _bb) { return getRootAsFlatModel(_bb, new FlatModel()); }
  public static FlatModel getRootAsFlatModel(ByteBuffer _bb, FlatModel obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public FlatModel __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String modelName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer modelNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public msge.std.FlatVec3 translation() { return translation(new msge.std.FlatVec3()); }
  public msge.std.FlatVec3 translation(msge.std.FlatVec3 obj) { int o = __offset(6); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public msge.std.FlatVec3 rotation() { return rotation(new msge.std.FlatVec3()); }
  public msge.std.FlatVec3 rotation(msge.std.FlatVec3 obj) { int o = __offset(8); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }
  public msge.std.FlatVec3 scale() { return scale(new msge.std.FlatVec3()); }
  public msge.std.FlatVec3 scale(msge.std.FlatVec3 obj) { int o = __offset(10); return o != 0 ? obj.__init(o + bb_pos, bb) : null; }

  public static void startFlatModel(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addModelName(FlatBufferBuilder builder, int modelNameOffset) { builder.addOffset(0, modelNameOffset, 0); }
  public static void addTranslation(FlatBufferBuilder builder, int translationOffset) { builder.addStruct(1, translationOffset, 0); }
  public static void addRotation(FlatBufferBuilder builder, int rotationOffset) { builder.addStruct(2, rotationOffset, 0); }
  public static void addScale(FlatBufferBuilder builder, int scaleOffset) { builder.addStruct(3, scaleOffset, 0); }
  public static int endFlatModel(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
};

